### ISSUE TITLE
Implementation to other HPC systems

### ISSUE THREAD

**Issue by bashirhamidi** [wyim-pgl/DCBLAST#2]
Dear @ascendo, 
I read your paper and find your tool fascinating. Any plans of implementing a version of this for LSF? If not, do you have any suggestion on how I may go about speeding up blastn on an LSF cluster?

**Comment by wyim-pgl** [comment]
I don't have any LSF environment so I cannot test it.

**Comment by mmokrejs** [comment]
But could you provide with the `--dry-run` an output file containing the shell commands to be executed (to actually submit the jobs)? People could check the generated commands, fix the syntax and report back.
