### ISSUE TITLE
slurm script error:  dcblast_merge.sh: command not found

### ISSUE THREAD

**Issue by gexijin** [wyim-pgl/DCBLAST#3]
I tried it and got an error 
dcblast_split.sh: command not found
dcblast_merge.sh: command not found

I solved this issue by editing the line 56 and 57 from:
my $dcblast_blastcmd = 'dcblast_blastcmd.sh';
my $dcblast_mergecmd = 'dcblast_merge.sh';

To: 
my $dcblast_blastcmd = './dcblast_blastcmd.sh';
my $dcblast_mergecmd = './dcblast_merge.sh';

The system now can find the two scripts.

**Comment by wyim-pgl** [comment]
Thanks!
