### ISSUE TITLE
Support for Torque/PBS

### ISSUE THREAD

**Issue by mmokrejs** [wyim-pgl/DCBLAST#4]
Hi,
  I would like to use dcblast to submit jobs to PBSpro. It could use a template file and replace the variables. For my purposes the following template would be enough.

```
#PBS -S $my_shell
#PBS -q $queue_name
#PBS -N ${job_prefix}_${chunk_id}
#PBS -l select=1:ncpus=24,walltime=144:00:00
#PBS -A $project_name
#PBS -M $email
#PBS -m ea

cd $PBS_O_WORKDIR || exit 255

$blastcmd" "${args}" "${other_user_opts}"
```

The command to submit a job is:

`qsub "${pbs_script_filename}"`

**Comment by wyim-pgl** [comment]
We don't have Torque/PBS.
But you can fix the code and pull request.
