### ISSUE TITLE
PBS code hack?

### ISSUE THREAD

**Issue by StephenWist** [wyim-pgl/DCBLAST#6]
> PBS & LSF need simple code hack. If you need it please request through issue.

I am running dcblast.pl through PBS and only the first result file gets written-no other results files are created. Pls help. 

See my config below:
`[dcblast]
##Name of job (will use for SGE job submission name)
job_name_prefix=dcblast_benchmark

[blast]
##BLAST options

##BLAST path (your blast+ path)
path=/data-fastpool/ncbi-blast-2.10.0+/bin

##DB path (build your own BLAST DB)
##example
##makeblastdb -in example/test_db.fas -dbtype nucl (for nucleotide sequence)
##makeblastdb -in example/your-protein-db.fas -dbtype prot (for protein sequence)
db=/data-fastpool/FELIX/blastdb/AllProteins/upkb_reviewed/upkb_bact_swissprot.fasta

##Evalue cut-off (See BLAST manual)
evalue=1e-05

##number of threads in each job. If your CPU is AMD it needs to be set 1.
num_threads=12

##Max target sequence output (See BLAST manual)
max_target_seqs=1

##Output format (See BLAST manual)
outfmt=6

##any other option can be add it this area
#num_alignments=1
#seg=yes
#soft_masking=true
#lcase_masking=
#max_hsps=1
#matrix=BLOSUM62
#gapopen=11
#gapextend=1

[sge]
##Grid job submission commands
##please check your job submission scripts
##Especially Queue name (q) and Threads option (pe) will be different depends on your system
M=stephen.wist@noblis.org
d=/data-fastpool/FELIX/blastdb/AllProteins/upkb_reviewed
o=/data-fastpool/FELIX/working/swist/dcblast_test
e=/data-fastpool/FELIX/working/swist/dcblast_test
l=walltime=48:00:00,nodes=1:ppn=12,pmem=6gb
m=abe`

**Comment by wyim-pgl** [comment]
sorry for the late reply.
PBS needs main code hack since they use the different array of job submission. We don't have any PBS HPC system. I cannot test it.
